AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: A serverless PDF conversion
Parameters:
  LambdaLayerArn:
    Type: String
    Default: 'arn:aws:lambda:us-east-1:818931230230:layer:pandoc:6'
  ConversionFileType:
    Type: String
    Default: docx
  ConversionMimeType:
    Type: String
    Default: application/vnd.openxmlformats-officedocument.wordprocessingml.document
Resources:
  UploadBucket:
    Type: AWS::S3::Bucket

  ResultsBucket:
    Type: AWS::S3::Bucket

  ConvertFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Timeout: 180
      MemorySize: 512
      Runtime: nodejs8.10
      CodeUri: src/
      Layers:
        - !Ref LambdaLayerArn
      Policies:
      - S3CrudPolicy:
          BucketName: !Sub "${AWS::StackName}-*"
      Environment:
        Variables:
          RESULTS_BUCKET_NAME: !Ref ResultsBucket
          EXTENSION: !Sub '.${ConversionFileType}'
          MIME_TYPE: !Ref ConversionMimeType
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: s3:ObjectCreated:*

Outputs:
    UploadBucket:
      Description: "Upload S3 bucket"
      Value: !Ref UploadBucket
    ResultsBucket:
      Description: "Results S3 bucket"
      Value: !Ref ResultsBucket

